### ISSUE TITLE
yqy_v2添加任务

### ISSUE THREAD

**Issue by BlueHtml** [zhaoshicong/QLScriptPublic#1]
你好，`yqy_v2`能把`每日累计使用5分钟`的任务加上吗？

**Comment by zhaoshicong** [comment]
可以试试&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoshicong/QLScriptPublic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 上午9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaoshicong/QLScriptPublic] yqy_v2添加任务 (Issue #1)





 
你好，yqy_v2能把每日累计使用5分钟的任务加上吗？

**Comment by zhaoshicong** [comment]
> 

最近2天可以添加下,

**Comment by zhaoshicong** [comment]
> 你好，能把的任务加上吗？`yqy_v2``每日累计使用5分钟`

优企盈开始黑号了

**Comment by BlueHtml** [comment]
@zhaoshicong 是不是`发帖`和`评论`这2个任务导致黑号的？无意义字符被官方注意到了？要不去掉这2个任务吧，反正也做不了（审核通不过）

**Comment by zhaoshicong** [comment]
极有可能啊！我还是先删除这两个任务吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaoshicong/QLScriptPublic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaoshicong/QLScriptPublic] yqy_v2添加任务 (Issue #1)





 
@zhaoshicong 是不是发帖和评论这2个任务导致黑号的？无意义字符被官方注意到了？要不去掉这2个任务吧，反正也做不了（审核通不过）

**Comment by zhaoshicong** [comment]
> @zhaoshicong 是不是和这2个任务导致黑号的？ 无意义字符被官方注意到了？ 要不去掉这2个任务吧，反正也做不了（审核通不过）`发帖``评论`

已经删除
